[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = true

[certificatesResolvers.lets-encrypt.acme]
  email = "PLEASEREPLACEMAIL"
  storage = "acme.json"
  [certificatesResolvers.lets-encrypt.acme.httpChallenge]
    entryPoint = "web"

[providers.docker]
  watch = true
  network = "web"

[providers.file]
  filename = "traefik_dynamic.toml"
  watch = true
[log]
  filePath = "/traefik/traefik.log"
  level = "DEBUG"
[accessLog]
  filePath = "/traefik/access.log"
  format = "json"
  bufferingSize = 100

  [accessLog.filters]    
    retryAttempts = true
    minDuration = "10ms"

